import Head from 'next/head'
import { AppLayout } from '../components/AppLayout'
import { ButtonLink } from '../components/ButtonLink'
import { Logo } from '../components/Logo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Logo />
        <ButtonLink href="/playGame">PLAY</ButtonLink>
      </AppLayout>
      <style jsx>
        {`
          div {
            height: 100%;
          }
        `}
      </style>
    </>
  )
}
