import Head from 'next/head'
import { AppLayout } from '../components/AppLayout'
import { ButtonLink } from '../components/ButtonLink'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <img src="https://brunao77.github.io/Higher-or-Lower-Youtube/assets/logoWhite.25805ac0.png" />
        <ButtonLink href="/playGame">PLAY</ButtonLink>
      </AppLayout>
      <style jsx>
        {`
          div {
            height: 100%;
          }
          img {
            width: max(30vw, 300px);
            height: max(20vw, 200px);
            margin-top: max(1vw, 40px);
            margin-bottom: max(1vw, 40px);
          }
        `}
      </style>
    </>
  )
}
